[havoc]
# pods with this prefix will be ignored when generating experiments
ignore_pods = ["geth", "mockserver", "-db-"]
# group labels containing these strings will be ignored when generating group experiments
ignore_group_labels = ["release"]
[havoc.failure]
# duration of a "failure" experiment
duration = "10s"
# percentage of pods experiments affect in groups, see group-failure key and dir when generated
group_percentage = "30"

[havoc.latency]
# duration of "latency" experiment
duration = "10s"
# constant latency to inject
latency = "300ms"
# percentage of pods experiments affect in groups, see group-failure key and dir when generated
group_percentage = "30"

[havoc.stress_memory]
# duration of "stress" experiment affecting pod memory
duration = "10s"
# amount of workers which occupies memory
workers = 1
# total amount of memory occupied
memory = "512MB"
# percentage of pods experiments affect in groups, see group-failure key and dir when generated
group_percentage = "30"

[havoc.stress_cpu]
# duration of "stress" experiment affecting pod CPU
duration = "10s"
# amount of workers which occupies cpu
workers = 1
# amount of CPU core utilization, 100 means 1 worker will consume 1 cpu, 2 workers + 100 load = 2 CPUs
load = 100
# percentage of pods experiments affect in groups, see group-failure key and dir when generated
group_percentage = "30"

[havoc.external_targets]
# duration of "external" experiment
duration = "1m"
# URL of external service that'd fail to resolve
urls = ["www.google.com"]

[havoc.monkey]
# havoc monkey mode:
# seq - runs all experiments from all dirs sequentially one time
# rand - runs random experiments from all dirs
mode = "seq"
# duration of havoc monkey
duration = "3m"
# dir is a custom dir you can select, if null monkey will create a new dir
#dir = "custom-experiments"
# cooldown between experiments
cooldown = "10s"
